In [ ]:
import pandas as pd
from google.colab import files

# =====================================================
# Upload file CSV
# =====================================================
uploaded = files.upload()
file_names = list(uploaded.keys())

print("Urutan file yang akan dibaca:")
for i, f in enumerate(file_names, 1):
    print(f"{i}. {f}")

df_list = []

# =====================================================
# Membaca dan menggabungkan setiap file CSV
# =====================================================
for file in file_names:
    try:
        df = pd.read_csv(
            file,
            encoding="utf-8",
            quotechar='"',
            doublequote=True,
            escapechar=None,
            on_bad_lines='warn'
        )
    except Exception as e:
        print(f"Error membaca {file}: {e}")
        continue

    # Menambahkan kolom sumber
    df["sumber"] = file

    # Konversi kolom tanggal ke datetime
    if 'tanggal' in df.columns:
        df['tanggal'] = pd.to_datetime(df['tanggal'], errors='coerce')

    # Mengurutkan berdasarkan tanggal
    if 'tanggal' in df.columns:
        df = df.sort_values('tanggal', ascending=True).reset_index(drop=True)

    print(f"{file}: {len(df)} baris berhasil dibaca")
    if 'tanggal' in df.columns:
        print(f"  Tanggal paling awal : {df['tanggal'].min()}")
        print(f"  Tanggal paling akhir: {df['tanggal'].max()}\n")

    df_list.append(df)

print("=" * 70)
print(f"Jumlah file yang dibaca: {len(df_list)}\n")

# =====================================================
# Menggabungkan seluruh DataFrame
# =====================================================
df_gabungan = pd.concat(df_list, ignore_index=True)

print(f"Total data setelah digabung: {len(df_gabungan)}")

# Standarisasi nama kolom
df_gabungan = df_gabungan.rename(columns={
    "userName": "nama",
    "score": "rating",
    "content": "ulasan",
    "at": "tanggal"
})

# =====================================================
# ANALISIS DESKRIPTIF DATASET
# =====================================================
print("\nANALISIS DESKRIPTIF DATASET")

# Jumlah baris dan kolom
print(f"Jumlah baris : {df_gabungan.shape[0]}")
print(f"Jumlah kolom : {df_gabungan.shape[1]}\n")

# Informasi tipe data
print("Informasi Tipe Data:")
df_gabungan.info()

# Ringkasan deskriptif per kolom
print("\nRingkasan Deskriptif per Kolom:")
deskriptif = pd.DataFrame({
    "Kolom": df_gabungan.columns,
    "Tipe Data": df_gabungan.dtypes.astype(str),
    "Count": df_gabungan.count(),
    "Unique": df_gabungan.nunique(),
    "Missing Values": df_gabungan.isnull().sum()
})

display(deskriptif)

# =====================================================
# Informasi tambahan
# =====================================================
print("\nDistribusi data berdasarkan sumber:")
print(df_gabungan['sumber'].value_counts())

print("\n5 data pertama:")
display(df_gabungan.head())

print("\n5 data terakhir:")
display(df_gabungan.tail())

# =====================================================
# Simpan hasil
# =====================================================
output_file = "ulasan_plnmobile.csv"
df_gabungan.to_csv(output_file, index=False, encoding="utf-8-sig")

print(f"\nFile disimpan sebagai: {output_file}")
files.download(output_file)

Saving ulasan_plnmobile_googleplaystore.csv to ulasan_plnmobile_googleplaystore.csv
Saving ulasan_plnmobile_applestore.csv to ulasan_plnmobile_applestore.csv
Urutan file yang akan dibaca:
1. ulasan_plnmobile_googleplaystore.csv
2. ulasan_plnmobile_applestore.csv
ulasan_plnmobile_googleplaystore.csv: 19643 baris berhasil dibaca
  Tanggal paling awal : 2025-09-26 00:01:27
  Tanggal paling akhir: 2025-10-25 23:58:50

ulasan_plnmobile_applestore.csv: 846 baris berhasil dibaca
  Tanggal paling awal : 2025-09-26 05:08:08-07:00
  Tanggal paling akhir: 2025-10-26 13:21:41-07:00

======================================================================
Jumlah file yang dibaca: 2

Total data setelah digabung: 20489

ANALISIS DESKRIPTIF DATASET
Jumlah baris : 20489
Jumlah kolom : 5

Informasi Tipe Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20489 entries, 0 to 20488
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nama     20489 non-null  object
 1   rating   16346 non-null  float64
 2   ulasan   16346 non-null  object
 3   tanggal  16346 non-null  object
 4   sumber   20489 non-null  object
dtypes: float64(1), object(4)
memory usage: 800.5+ KB

Ringkasan Deskriptif per Kolom:

           Kolom Tipe Data  Count  Unique  Missing Values
nama        nama    object  20489   20218               0
rating    rating   float64  16346       5            4143
ulasan    ulasan    object  16346   12606            4143
tanggal  tanggal    object  16346   16216            4143
sumber    sumber    object  20489       2               0

Distribusi data berdasarkan sumber:
sumber
ulasan_plnmobile_googleplaystore.csv    19643
ulasan_plnmobile_applestore.csv           846
Name: count, dtype: int64

5 data pertama:

,nama,rating,ulasan,tanggal,sumber
0,Nuraini Aini,5.0,yes mantap🤗🤗🤗🙏🙏🙏,2025-09-26 00:01:27,ulasan_plnmobile_googleplaystore.csv
1,kus wanto,5.0,aplikasi yg sangat bermanfaat utk urusan kelis...,2025-09-26 00:05:57,ulasan_plnmobile_googleplaystore.csv
2,askhar muda,5.0,sangat membantu proses pengaduan,2025-09-26 00:08:49,ulasan_plnmobile_googleplaystore.csv
3,Heru Cahyono,5.0,Lebih mudah dan cepat tanggap,2025-09-26 00:09:27,ulasan_plnmobile_googleplaystore.csv
4,Dikdo Wibowo,5.0,bagus,2025-09-26 00:13:31,ulasan_plnmobile_googleplaystore.csv

5 data terakhir:

,nama,rating,ulasan,tanggal,sumber
20484,gus.arief,5.0,aplikasinya sangat informatif untuk perihal ke...,2025-10-26 06:32:35-07:00,ulasan_plnmobile_applestore.csv
20485,Jecarli sepucer,5.0,Mengadukan laporan menjadi lebih mudah dan ges...,2025-10-26 06:33:23-07:00,ulasan_plnmobile_applestore.csv
20486,Ardypv,5.0,PLN Mobile sangat membantu. Fitur lebih lengka...,2025-10-26 08:25:11-07:00,ulasan_plnmobile_applestore.csv
20487,Muhamad Raffi,1.0,Responnya tindak lanjut laporan lama,2025-10-26 11:02:20-07:00,ulasan_plnmobile_applestore.csv
20488,andi yuni hidayat,5.0,penanganannya cepet banget dan sangat membantu,2025-10-26 13:21:41-07:00,ulasan_plnmobile_applestore.csv

File disimpan sebagai: ulasan_plnmobile.csv